# Site
name: "MSWDO - Calape"
title: "MSWDO - Calape"
description: "Municipal Social Welfare and Development Office"
logo: 'assets/images/logo.png'
favicon: 'https://calape.ph/icons/favicon-32x32.png'
baseurl: /
google_analytics: ''
disqus: 'mswdo-calape'
disqus_enable: false
#mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  mswdo:
    name: MSWDO
    display_name: MSWDO
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: mswdo@calape.ph
    web: https://mswdo.calape.ph
    twitter: https://mswdo.calape.ph/social-media
    description: "Municipal Social Welfare and Development Office"
  dswd:
    name: DSWD
    display_name: DSWD    
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: mswdo@calape.ph
    web: https://www.dswd.gov.ph
    twitter: https://twitter.com/dswdserves
    description: "Department of Social Welfare and Development"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-xxx"
adsense-data-ad-slot: "xxx"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
